### Simple Chat
GET http://localhost:18080/helloworld/simple/chat?query=你是谁？

### 流式调用 Stream Chat
GET http://localhost:18080/helloworld/stream/chat?
    query=你好啊，请简单介绍一下你自己


### 带有上下文（记忆）
GET http://127.0.0.1:18080/helloworld/advisor/chat/123?query=你好，我叫牧生，之后的会话中都带上我的名字
### 带有上下文（记忆）
GET http://127.0.0.1:18080/helloworld/advisor/chat/123?query=我叫什么名字？



